BASE_PATH = "sample_images/"
BG_IMG_PATH = BASE_PATH + "background_images/"
RECT_IMG_PATH = BASE_PATH + "rect_images/"

IMAGE_WIDTH = 256
IMAGE_HEIGHT = 256
MAX_RECT_WIDTH = 248
MAX_RECT_HEIGHT = 248
MIN_RECT_WIDTH = 45
MIN_RECT_HEIGHT = 45

BLUR_EDGE_RADIUS = 4
